name: Generate Trophies

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: soulteary/github-profile-trophy@main
        with:
          args: -u ZonicExists -t tokyonight --no-frame --no-bg
      - name: Commit and Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Update trophies" || exit 0
          git push
